table Analytics

	column TipoCredito
		dataType: int64
		summarizeBy: none
		sourceColumn: TipoCredito

	column TipoLaboral
		dataType: string
		summarizeBy: none
		sourceColumn: TipoLaboral

	column PagoATiempo
		dataType: int64
		summarizeBy: none
		sourceColumn: PagoATiempo

	column Creditos
		dataType: int64
		summarizeBy: none
		sourceColumn: Creditos

	column Capital
		dataType: double
		summarizeBy: none
		sourceColumn: Capital

	column SaldoMora
		dataType: double
		summarizeBy: none
		sourceColumn: SaldoMora

	measure KPI_Creditos = SUM(Analytics[Creditos])
		formatString: #,0.00
		displayFolder: KPIs

	measure KPI_Capital = SUM(Analytics[Capital])
		formatString: #,0.00
		displayFolder: KPIs

	measure KPI_TasaPagoATiempo = DIVIDE(CALCULATE(SUM(Analytics[Creditos]), Analytics[PagoATiempo] = 1), SUM(Analytics[Creditos]))
		formatString: #,0.00
		displayFolder: KPIs

	partition Analytics = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents(DataFolder & "analytics.csv"), [Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
				    Headers = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    Typed = Table.TransformColumnTypes(Headers, {{"TipoCredito", Int64.Type}, {"TipoLaboral", type text}, {"PagoATiempo", Int64.Type}, {"Creditos", Int64.Type}, {"Capital", type number}, {"SaldoMora", type number}}, "en-US")
				in
				    Typed
